export interface LocationData {
    wilayah: string | null
    manager: string | null
    unit: string | null
}

export type WoodType = 'Jati' | 'Rimba'

export type RSTProductType =
    | 'BBI Venir Stock / Blockware'
    | 'BBI Lamela (Lamstock)'
    | 'RST Garden Furniture'
    | 'RST Housing Componen'
    | 'RST Flooring'
    | 'RST Decking'
    | 'RST Lamparquet'
    | 'RST Listoni'
    | 'RST Skirting'
    | 'RST Parket Block'
    | 'RST Parket Stock'
    | 'RST Reng'
    | 'RST List'
    | 'BBI CLT'
    | 'Jeblosan'
    | 'BBI Componen'
    | 'BBI Flooring'
    | 'BBI Finger Joint Laminating'
    | 'RST Longstrip'
    | 'RST Kayu KAM'
    | 'Afval kayu'

export interface RSTProduct {
    id: number
    ketersediaan: 'Tersedia' | 'Dipesan' | 'Berkomitmen' | 'Ditahan'
    tpk: string
    jenisKayu: WoodType
    productType: RSTProductType
    noKapling: string
    sertifikasi: string
    hargaAwal: number
    difPersen: number
    totalDif: number
    hargaAkhir: number
    noBlok: string
    sortimen: string
    panjang: number
    lebar: number | null
    tebalDiameter: string
    mutu: 'U' | 'P' | 'D' | 'T'
    jumlah: number
    volume: number
    jenisTebangan: string
    usiaTayangKapling: string
    tahunKapling: number
    tahunProduksi: number
    unit: string
}

export const RST_PRODUCT_TYPES_ARRAY: RSTProductType[] = [
    'BBI Venir Stock / Blockware',
    'BBI Lamela (Lamstock)',
    'RST Garden Furniture',
    'RST Housing Componen',
    'RST Flooring',
    'RST Decking',
    'RST Lamparquet',
    'RST Listoni',
    'RST Skirting',
    'RST Parket Block',
    'RST Parket Stock',
    'RST Reng',
    'RST List',
    'BBI CLT',
    'Jeblosan',
    'BBI Componen',
    'BBI Flooring',
    'BBI Finger Joint Laminating',
    'RST Longstrip',
    'RST Kayu KAM',
    'Afval kayu'
]

export type FinishedCategory = 'Home Decor' | 'Home Construction'

export const FINISHED_CATEGORIES_ARRAY: FinishedCategory[] = [
    'Home Decor',
    'Home Construction'
]

export interface FinishedProduct {
    id: number
    name: string
    category: FinishedCategory
    subCategory: string
    woodType: WoodType
    dimensions: string
    price: number
    stock: number
    grade: 'A' | 'B' | 'C'
    image: string
    unit: string
    wilayah: string
    sertifikat: string
}

export const rstData: RSTProduct[] = [
    {
        id: 1,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Flooring',
        noKapling: 'KPL-001',
        sertifikasi: 'FSC-PURE',
        hargaAwal: 15000000,
        difPersen: 5,
        totalDif: 750000,
        hargaAkhir: 15750000,
        noBlok: 'B-12',
        sortimen: 'AIII',
        panjang: 200,
        lebar: null,
        tebalDiameter: '24-30"',
        mutu: 'U',
        jumlah: 10,
        volume: 2.48,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '15 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2023,
        unit: 'PIK Gresik',
    },
    {
        id: 2,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Rimba',
        productType: 'BBI Lamela (Lamstock)',
        noKapling: 'KPL-002',
        sertifikasi: 'SVLK',
        hargaAwal: 8000000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 8000000,
        noBlok: 'B-05',
        sortimen: 'AII',
        panjang: 300,
        lebar: null,
        tebalDiameter: '18-24"',
        mutu: 'P',
        jumlah: 25,
        volume: 1.24,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '30 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2022,
        unit: 'PIK Gresik',
    },
    {
        id: 5,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Decking',
        noKapling: 'KPL-003',
        sertifikasi: 'FSC-MIX',
        hargaAwal: 18000000,
        difPersen: 3,
        totalDif: 540000,
        hargaAkhir: 18540000,
        noBlok: 'B-15',
        sortimen: 'AIV',
        panjang: 250,
        lebar: 15,
        tebalDiameter: '30-40"',
        mutu: 'U',
        jumlah: 15,
        volume: 3.52,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '20 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Gresik',
    },
    {
        id: 6,
        ketersediaan: 'Berkomitmen',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Housing Componen',
        noKapling: 'KPL-004',
        sertifikasi: 'FSC-PURE',
        hargaAwal: 14000000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 14000000,
        noBlok: 'A-02',
        sortimen: 'AIII',
        panjang: 220,
        lebar: null,
        tebalDiameter: '20-25"',
        mutu: 'P',
        jumlah: 8,
        volume: 1.85,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '45 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2023,
        unit: 'PIK Gresik',
    },
    {
        id: 7,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Rimba',
        productType: 'RST Reng',
        noKapling: 'KPL-005',
        sertifikasi: 'SVLK',
        hargaAwal: 6500000,
        difPersen: 2,
        totalDif: 130000,
        hargaAkhir: 6630000,
        noBlok: 'B-09',
        sortimen: 'AI',
        panjang: 400,
        lebar: 3,
        tebalDiameter: '10-15"',
        mutu: 'D',
        jumlah: 100,
        volume: 1.20,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '10 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Gresik',
    },
    {
        id: 8,
        ketersediaan: 'Ditahan',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Parket Stock',
        noKapling: 'KPL-006',
        sertifikasi: 'FSC-PURE',
        hargaAwal: 22000000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 22000000,
        noBlok: 'C-10',
        sortimen: 'AV',
        panjang: 180,
        lebar: null,
        tebalDiameter: '40-50"',
        mutu: 'U',
        jumlah: 5,
        volume: 4.12,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '60 Hari',
        tahunKapling: 2022,
        tahunProduksi: 2022,
        unit: 'PIK Gresik',
    },
    {
        id: 9,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Rimba',
        productType: 'BBI Componen',
        noKapling: 'KPL-007',
        sertifikasi: 'SVLK',
        hargaAwal: 9500000,
        difPersen: 1,
        totalDif: 95000,
        hargaAkhir: 9595000,
        noBlok: 'B-21',
        sortimen: 'AII',
        panjang: 350,
        lebar: 20,
        tebalDiameter: '15-20"',
        mutu: 'T',
        jumlah: 40,
        volume: 2.15,
        jenisTebangan: 'Salvage',
        usiaTayangKapling: '5 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Gresik',
    },
    {
        id: 10,
        ketersediaan: 'Dipesan',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Garden Furniture',
        noKapling: 'KPL-008',
        sertifikasi: 'FSC-MIX',
        hargaAwal: 17500000,
        difPersen: 4,
        totalDif: 700000,
        hargaAkhir: 18200000,
        noBlok: 'A-14',
        sortimen: 'AIII',
        panjang: 210,
        lebar: null,
        tebalDiameter: '25-30"',
        mutu: 'P',
        jumlah: 12,
        volume: 2.88,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '12 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2023,
        unit: 'PIK Gresik',
    },
    {
        id: 11,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Listoni',
        noKapling: 'KPL-009',
        sertifikasi: 'FSC-PURE',
        hargaAwal: 13500000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 13500000,
        noBlok: 'B-01',
        sortimen: 'AII',
        panjang: 300,
        lebar: 10,
        tebalDiameter: '15-20"',
        mutu: 'D',
        jumlah: 60,
        volume: 1.45,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '25 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2023,
        unit: 'PIK Gresik',
    },
    {
        id: 12,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Rimba',
        productType: 'RST Longstrip',
        noKapling: 'KPL-010',
        sertifikasi: 'SVLK',
        hargaAwal: 11000000,
        difPersen: 2,
        totalDif: 220000,
        hargaAkhir: 11220000,
        noBlok: 'D-05',
        sortimen: 'AIV',
        panjang: 500,
        lebar: null,
        tebalDiameter: '35-45"',
        mutu: 'U',
        jumlah: 4,
        volume: 5.60,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '8 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Gresik',
    },
    {
        id: 3,
        ketersediaan: 'Dipesan',
        tpk: 'TPK Saradan',
        jenisKayu: 'Jati',
        productType: 'RST Garden Furniture',
        noKapling: 'KPL-045',
        sertifikasi: 'FSC-MIX',
        hargaAwal: 12000000,
        difPersen: 2,
        totalDif: 240000,
        hargaAkhir: 12240000,
        noBlok: 'C-01',
        sortimen: 'AIII',
        panjang: 250,
        lebar: null,
        tebalDiameter: '12-18"',
        mutu: 'D',
        jumlah: 5,
        volume: 0.89,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '5 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Saradan',
    },
    {
        id: 4,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Saradan',
        jenisKayu: 'Rimba',
        productType: 'RST Housing Componen',
        noKapling: 'KPL-046',
        sertifikasi: 'SVLK',
        hargaAwal: 5000000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 5000000,
        noBlok: 'C-02',
        sortimen: 'AII',
        panjang: 400,
        lebar: null,
        tebalDiameter: '20-26"',
        mutu: 'T',
        jumlah: 50,
        volume: 1.56,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '10 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2023,
        unit: 'PIK Saradan',
    },
    // ---- ADDED MISSING PERMUTATIONS FOR JATI ----
    {
        id: 13,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Jati',
        productType: 'RST Reng',
        noKapling: 'KPL-050',
        sertifikasi: 'FSC-MIX',
        hargaAwal: 7500000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 7500000,
        noBlok: 'E-01',
        sortimen: 'AIII',
        panjang: 400,
        lebar: 4,
        tebalDiameter: '3-4"',
        mutu: 'P',
        jumlah: 150,
        volume: 2.1,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '12 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Gresik',
    },
    {
        id: 14,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Saradan',
        jenisKayu: 'Jati',
        productType: 'RST Longstrip',
        noKapling: 'KPL-051',
        sertifikasi: 'FSC-PURE',
        hargaAwal: 15000000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 15000000,
        noBlok: 'A-20',
        sortimen: 'AV',
        panjang: 500,
        lebar: 15,
        tebalDiameter: '30-45"',
        mutu: 'U',
        jumlah: 20,
        volume: 3.5,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '5 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2023,
        unit: 'PIK Saradan',
    },
    // ---- ADDED MISSING PERMUTATIONS FOR RIMBA ----
    {
        id: 15,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Rimba',
        productType: 'RST Flooring',
        noKapling: 'KPL-060',
        sertifikasi: 'SVLK',
        hargaAwal: 9500000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 9500000,
        noBlok: 'B-10',
        sortimen: 'AII',
        panjang: 200,
        lebar: 10,
        tebalDiameter: '18"',
        mutu: 'P',
        jumlah: 50,
        volume: 1.8,
        jenisTebangan: 'Tebas Habis',
        usiaTayangKapling: '15 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2023,
        unit: 'PIK Gresik',
    },
    {
        id: 16,
        ketersediaan: 'Dipesan',
        tpk: 'TPK Saradan',
        jenisKayu: 'Rimba',
        productType: 'RST Decking',
        noKapling: 'KPL-061',
        sertifikasi: 'SVLK',
        hargaAwal: 11000000,
        difPersen: 2,
        totalDif: 220000,
        hargaAkhir: 11220000,
        noBlok: 'C-05',
        sortimen: 'AIV',
        panjang: 300,
        lebar: 15,
        tebalDiameter: '25-35"',
        mutu: 'U',
        jumlah: 40,
        volume: 2.2,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '21 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2024,
        unit: 'PIK Saradan',
    },
    {
        id: 17,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Gresik',
        jenisKayu: 'Rimba',
        productType: 'RST Garden Furniture',
        noKapling: 'KPL-062',
        sertifikasi: 'SVLK',
        hargaAwal: 8500000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 8500000,
        noBlok: 'D-02',
        sortimen: 'AII',
        panjang: 250,
        lebar: null,
        tebalDiameter: '15-20"',
        mutu: 'D',
        jumlah: 35,
        volume: 1.5,
        jenisTebangan: 'Salvage',
        usiaTayangKapling: '3 Hari',
        tahunKapling: 2024,
        tahunProduksi: 2023,
        unit: 'PIK Gresik',
    },
    {
        id: 18,
        ketersediaan: 'Tersedia',
        tpk: 'TPK Saradan',
        jenisKayu: 'Rimba',
        productType: 'RST Listoni',
        noKapling: 'KPL-063',
        sertifikasi: 'SVLK',
        hargaAwal: 7800000,
        difPersen: 0,
        totalDif: 0,
        hargaAkhir: 7800000,
        noBlok: 'A-12',
        sortimen: 'AI',
        panjang: 300,
        lebar: 10,
        tebalDiameter: '12-16"',
        mutu: 'T',
        jumlah: 120,
        volume: 2.5,
        jenisTebangan: 'Selektif',
        usiaTayangKapling: '18 Hari',
        tahunKapling: 2023,
        tahunProduksi: 2023,
        unit: 'PIK Saradan',
    },
]

export const finishedProducts: FinishedProduct[] = [
    {
        id: 1,
        name: 'Meja Makan Jati Minimalis',
        category: 'Home Decor',
        subCategory: 'Meja',
        woodType: 'Jati',
        dimensions: '200x100x75cm',
        price: 3500000,
        stock: 20,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Gresik',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'FSC-PURE',
    },
    {
        id: 2,
        name: 'Pintu Utama Rimba Solid',
        category: 'Home Construction',
        subCategory: 'Pintu',
        woodType: 'Rimba',
        dimensions: '90x210x4cm',
        price: 1250000,
        stock: 45,
        grade: 'B',
        image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Gresik',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'SVLK',
    },
    {
        id: 3,
        name: 'Kursi Teras Jati Retro',
        category: 'Home Decor',
        subCategory: 'Kursi',
        woodType: 'Jati',
        dimensions: '55x60x85cm',
        price: 850000,
        stock: 120,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Saradan',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'FSC-MIX',
    },
    {
        id: 4,
        name: 'Kusen Jendela Rimba',
        category: 'Home Construction',
        subCategory: 'Kusen',
        woodType: 'Rimba',
        dimensions: '60x120x12cm',
        price: 450000,
        stock: 80,
        grade: 'C',
        image: 'https://images.unsplash.com/photo-1510074377623-8cf13fb86c08?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Saradan',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'SVLK',
    },
    {
        id: 5,
        name: 'Almari Pakaian 3 Pintu',
        category: 'Home Decor',
        subCategory: 'Almari',
        woodType: 'Jati',
        dimensions: '150x60x200cm',
        price: 5200000,
        stock: 12,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Ngawi',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'FSC-PURE',
    },
    {
        id: 6,
        name: 'Balok Rimba 6/12',
        category: 'Home Construction',
        subCategory: 'Balok',
        woodType: 'Rimba',
        dimensions: '6x12x400cm',
        price: 180000,
        stock: 200,
        grade: 'B',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Ngawi',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'SVLK',
    },
    {
        id: 7,
        name: 'Tempat Tidur King Size',
        category: 'Home Decor',
        subCategory: 'Tempat Tidur',
        woodType: 'Jati',
        dimensions: '180x200cm',
        price: 4800000,
        stock: 10,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Jatirogo',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'FSC-MIX',
    },
    {
        id: 8,
        name: 'Reng Rimba 2/3',
        category: 'Home Construction',
        subCategory: 'Reng',
        woodType: 'Rimba',
        dimensions: '2x3x300cm',
        price: 25000,
        stock: 1500,
        grade: 'C',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Jatirogo',
        wilayah: 'Wilayah Jawa Timur',
        sertifikat: 'SVLK',
    },
    // ---- ADDED MISSING PERMUTATIONS: RIMBA - HOME DECOR ----
    {
        id: 9,
        name: 'Meja Makan Rimba Natural',
        category: 'Home Decor',
        subCategory: 'Meja',
        woodType: 'Rimba',
        dimensions: '200x100x75cm',
        price: 1800000,
        stock: 25,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Cepu',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'SVLK',
    },
    {
        id: 10,
        name: 'Kursi Teras Rimba Minimalis',
        category: 'Home Decor',
        subCategory: 'Kursi',
        woodType: 'Rimba',
        dimensions: '55x60x85cm',
        price: 450000,
        stock: 80,
        grade: 'B',
        image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Cepu',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'SVLK',
    },
    {
        id: 11,
        name: 'Almari Pakaian 2 Pintu Rimba',
        category: 'Home Decor',
        subCategory: 'Almari',
        woodType: 'Rimba',
        dimensions: '100x60x200cm',
        price: 2400000,
        stock: 15,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Randublatung',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'SVLK',
    },
    {
        id: 12,
        name: 'Tempat Tidur Queen Size Rimba',
        category: 'Home Decor',
        subCategory: 'Tempat Tidur',
        woodType: 'Rimba',
        dimensions: '160x200cm',
        price: 2100000,
        stock: 20,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Randublatung',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'SVLK',
    },
    // ---- ADDED MISSING PERMUTATIONS: JATI - HOME CONSTRUCTION ----
    {
        id: 13,
        name: 'Pintu Utama Jati Solid 3D',
        category: 'Home Construction',
        subCategory: 'Pintu',
        woodType: 'Jati',
        dimensions: '100x220x5cm',
        price: 4500000,
        stock: 18,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Cepu',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'FSC-PURE',
    },
    {
        id: 14,
        name: 'Kusen Jendela Jati Utama',
        category: 'Home Construction',
        subCategory: 'Kusen',
        woodType: 'Jati',
        dimensions: '60x120x15cm',
        price: 1150000,
        stock: 40,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1510074377623-8cf13fb86c08?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Cepu',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'FSC-MIX',
    },
    {
        id: 15,
        name: 'Balok Jati 8/12',
        category: 'Home Construction',
        subCategory: 'Balok',
        woodType: 'Jati',
        dimensions: '8x12x400cm',
        price: 650000,
        stock: 60,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Randublatung',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'FSC-PURE',
    },
    {
        id: 16,
        name: 'Reng Jati Super 2/3',
        category: 'Home Construction',
        subCategory: 'Reng',
        woodType: 'Jati',
        dimensions: '2x3x300cm',
        price: 55000,
        stock: 500,
        grade: 'A',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
        unit: 'PIK Randublatung',
        wilayah: 'Wilayah Jawa Tengah',
        sertifikat: 'FSC-MIX',
    },
]
